version = 5.3.1
archive_dir = /etc/letsencrypt/archive/travelapp.space
cert = /etc/letsencrypt/live/travelapp.space/cert.pem
privkey = /etc/letsencrypt/live/travelapp.space/privkey.pem
chain = /etc/letsencrypt/live/travelapp.space/chain.pem
fullchain = /etc/letsencrypt/live/travelapp.space/fullchain.pem
[renewalparams]
account = 5e6faf7c3116953f82d523e667eab357
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
travelapp.space = /var/www/certbot
www.travelapp.space = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-02-14T07:14:29
